
#This file will be responsible for reading mp3 files generated by the googleTTS file and playing them directly, rather than opening in Windows.



import pyaudio
import pyttsx3
import speech_recognition as sr

def play_mp3(mp3_file):
    """
    Plays an MP3 file using PyAudio.
    """
    p = pyaudio.PyAudio()

    foundFormat = p.get_format_from_width(2)

    stream = p.open(format=pyaudio.paInt16, channels=1, rate=44100, output=True)
    data = open(mp3_file, 'rb').read()
    stream.write(data)
    stream.stop_stream()
    stream.close()
    p.terminate()

#Record audio from the microphone and return the text
def record_audio():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Say something!")
        audio = r.listen(source)
    try:
        text = r.recognize_google(audio)
        return text
    except:
        print("Sorry, I didn't get that.")


def main():
    text = record_audio()
    print(text)

if __name__ == "__main__":
    main()