import speech_recognition as sr

#from pydub import AudioSegment
#from pydub.playback import play

import vlc
import time



'''
#Takes a BytesIO object and play it via pydub as a mp3
#TODO partly works after adding ffmpeg to PATH but fails to run _winapi.createProcess due to permissions
   no willing to raise permission level of this to continue. 
 
def play_bytesIo_pydub(byteArray):
    AudioSegment.converter = "C:/programming/data/ffmpeg-7/bin"
    AudioSegment.ffmpeg = "C:/programming/data/ffmpeg-7/bin"
    AudioSegment.ffprobe ="C:/programming/data/ffmpeg-7/bin"
    sound = AudioSegment.from_mp3(byteArray)
    play(sound)

    '''


#Play an MP3 file, but will read an MP3 file.
#Note there is a delay between player.play() firing and player.is_playing() being true. the 0.05 second sleep time is a magic number that works locally.
#Not 100% sure i am satisfied with using VLC just yet but it seems to work for the moment.
def play_mp3_vlc(mp3_file):
    player = vlc.MediaPlayer(mp3_file)
    player.play()
    time.sleep(0.05)
    while player.is_playing():
        time.sleep(0.1)
    player.stop()

#Record audio from the microphone and return the text
#TODO make sure this doesn't save the audio somewhere without being maintained/deleted
def record_audio():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Say something!")
        audio = r.listen(source)
    try:
        text = r.recognize_google(audio)
        return text
    except:
        print("Sorry, I didn't get that.")


#just plays the helloworld mp3 generated by googleTTS. if it sounds like a brief blur there may be channel issues. 
def test_helloworld():
    play_mp3_vlc("C:/programming/data/sound/gtts/helloWorld.mp3")

#just to test things inline
def main():
    test_helloworld()
#    text = record_audio()
#    print(text)

if __name__ == "__main__":
    main()