
#This file will be responsible for reading mp3 files generated by the googleTTS file and playing them directly, rather than opening in Windows.
# Remove pyaudio because i don't want to convert to using WAV files.


import vlc
import time

def play_mp3(mp3_file):
    """
    Plays an MP3 file using vlc.
    """
    player = vlc.MediaPlayer(mp3_file)
    player.play()
    #Sleep as there is a very small delay in the player.is_playing() function being true after the above line.
    time.sleep(0.05)
    while player.is_playing():
        time.sleep(0.1)
    player.stop()
